#!/bin/bash
julia --project=docs -e '
    using Pkg
    Pkg.activate(joinpath(pwd(), "docs"))
    Pkg.develop(PackageSpec(path=pwd()))
    Pkg.instantiate()
    weave(joinpath(pwd(), "docs", "README.jmd"))'

if ! git diff --exit-code; then
    git commit -am 're-weave README'
    exit 1
else
    exit 0
fi
