#!/bin/bash
julia --project=docs -e '
    using Pkg
    Pkg.develop(PackageSpec(path=pwd()))
    Pkg.instantiate()
    using Weave
    weave("docs/README.jmd")'

# only do automatic commit if we are in a hook execution
# I don't know a great way to do this other than seeing if lines are passed
if [ $# -ne 0 ]; then
    # see if the code has changed and add a commit before pushing
    if ! git diff --exit-code README.md; then
        git add README.md
        git commit -m 're-weave README'
    fi
fi
exit 0 # push will execute
