#!/bin/bash
julia --project=docs -e '
    using Pkg
    Pkg.develop(PackageSpec(path=pwd()))
    Pkg.instantiate()
    using Weave
    weave("docs/README.jmd")'

# see if the code has changed and prevent pushing if true
git diff --exit-code README.md
